<Container>:
    rows: 3
    padding: 25

    texin: tin
    lain: lin

    Label:
        id: lin
        font_size:40
        text: 'Text'
    TextInput:
        id: tin
        size_hint: 1,.4
        multiline: False
        font_size: 40
    FloatLayout:
        Button:
            size_hint: .5,.4
            pos_hint:{"center_x":.5,"y":.1}
            text: 'Send'
            font_size:40
            on_press:
                root.change_text()
